set_lock_access_code:
  name: Set a access_code on a lock
  description: Set a access_code on a lock
  target:
    entity:
      integration: ha_seam
  fields:
    access_code:
      name: Access Code
      description: Code to set.
      required: true
      example: 1234
      selector:
        text:
    guest_name:
      name: Guest Name
      description: Guest Name to set.
      required: true
      example: John
      selector:
        text:
    starts_at:
      name: Starts At
      description: Code to start at.
      required: true
      example: 2023-01-01T16:00:00-0600
      selector:
        text:
    ends_at:
      name: Ends At
      description: Code to end at.
      required: true
      example: 2024-01-01T11:15:00-0600
      selector:
        text:
